apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator


images:
  - name: minio/operator
    newName: 709825985650.dkr.ecr.us-east-1.amazonaws.com/minio/enterprise-operator
    newTag: v4.4.3
  - name: minio/console
    newName: 709825985650.dkr.ecr.us-east-1.amazonaws.com/minio/enterprise-console
    newTag: v0.13.2-v2

resources:
  - github.com/minio/operator/resources/?ref=v4.4.3
  - nvme-i3en-12xlarge.yaml
  - hdd-d3en-12xlarge.yaml

patchesStrategicMerge:
  - overlays/console-deployment.yaml


patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: minio-operator-role
    path: overlays/patch-minio-operator-sa.yaml