apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator
images:
  - name: minio/operator
    newName: 709825985650.dkr.ecr.us-east-1.amazonaws.com/minio/enterprise-operator
    newTag: '5.0.10'
resources:
  - github.com/minio/operator/resources/?ref=v5.0.10
  - performance-optimized.yaml
  - capacity-optimized.yaml
patchesStrategicMerge:
  - overlays/deployment.yaml
patches:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: minio-operator-role
    path: overlays/patch-minio-operator-sa.yaml
