x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '4.4.14'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  deployerServiceAccount:
    description: >
      Creates app resources, including the MinIO Tenant CRD.
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups: ['apiextensions.k8s.io', 'rbac.authorization.k8s.io', 'app.k8s.io', 'storage.k8s.io']
            resources: ['customresourcedefinitions', 'clusterroles', 'clusterrolebindings', 'applications', 'storageclasses']
            verbs: ['*']

  images:
    '':
      properties:
        imageFull:
          type: FULL
        imageRepo: 
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
    operator:
      properties:
        imageOperatorlFull:
          type: FULL 
    console:
      properties:
        imageConsoleFull:
          type: FULL
    ubbagent:
      properties:
        imageUbbAgentFull:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  
required:
- name
- namespace