apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: example-eks-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m4.xlarge
    desiredCapacity: 4
    iam:
      withAddonPolicies:
        ebs: true
        awsLoadBalancerController: true
