apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio-tenant-1
  namespace: minio-tenant-1
scheduler:
  name: ""
spec:
  certConfig:
    commonName: '*.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local'
    dnsNames:
    - minio-tenant-1-ss-0-{0...3}.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local
    organizationName:
    - system:nodes
  configuration:
    name: minio-tenant-1-env-configuration
  image: minio/minio:RELEASE.2022-10-02T19-29-29Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  log:
    audit:
      diskCapacityGB: 5
    db:
      image: library/postgres:13
      initimage: busybox:1.33.1
      resources: {}
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
          name: minio-tenant-1-log
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "5368709120"
        status: {}
    image: minio/operator:v4.5.2
    resources: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-tenant-1
          topologyKey: kubernetes.io/hostname
    name: ss-0
    resources: {}
    servers: 4
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 256Gi
        storageClassName: gp2
      status: {}
    volumesPerServer: 1
  prometheus:
    diskCapacityGB: 5
    image: quay.io/prometheus/prometheus:latest
    initimage: busybox:1.33.1
    resources: {}
    sidecarimage: alpine
  requestAutoCert: true
  users:
  - name: minio-tenant-1-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}

---
apiVersion: v1
data:
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0iWFZGTkM5TTlSQTRUNkczRlNRRTYiCmV4cG9ydCBNSU5JT19ST09UX1BBU1NXT1JEPSJHVmNSRElTSTZweG9RRzdlbFVqYVFiN2tJZlRYeUNVUG42T1ZybWVtIgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-tenant-1-env-configuration
  namespace: minio-tenant-1

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: NDVVUEo2WVJCWjI0UjVZQUoxR0I=
  CONSOLE_SECRET_KEY: aUFQMkRUVTdZMGdoMW1HQlZIT0d0SWRsOEswbExoRnBuNEpnTGxBOA==
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-tenant-1-user-1
  namespace: minio-tenant-1